# Generated by Django 5.1 on 2024-09-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landingsection',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='landingsection',
            name='image',
        ),
        migrations.RemoveField(
            model_name='landingsection',
            name='order',
        ),
        migrations.AddField(
            model_name='landingsection',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
